//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONCORDIAUSER
    {
        public int ID { get; set; }
        public string ROLE { get; set; }
        public string EMAIL { get; set; }
        public string NETNAME { get; set; }
        public string OAUTHID { get; set; }
    }
}
