//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT_USERS
    {
        public string EVENT_ID { get; set; }
        public string STUDENT_NETNAME_FK { get; set; }
        public string ROLE { get; set; }
        public string STATUS { get; set; }
        public string ID_PK { get; set; }
    
        public virtual EVENT EVENT { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
