//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EVENT()
        {
            this.EVENT_USERS = new HashSet<EVENT_USERS>();
        }
    
        public string ID_PK { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string LOCATION { get; set; }
        public string ROOM { get; set; }
        public System.DateTime TIME_BEGIN { get; set; }
        public System.DateTime TIME_END { get; set; }
        public string TYPE { get; set; }
        public string EVENT_USER_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVENT_USERS> EVENT_USERS { get; set; }
        public virtual EVENT_USERS EVENT_USERS1 { get; set; }
    }
}
