//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PICTURE
    {
        public int ID { get; set; }
        public double PENDING { get; set; }
        public Nullable<double> APPROVED { get; set; }
        public byte[] PICTURE1 { get; set; }
        public System.DateTime UPLOADEDDATE { get; set; }
    }
}
