//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PICTUREUPDATESETTING
    {
        public short YEAR { get; set; }
        public System.DateTime STARDATE { get; set; }
        public System.DateTime ENDDATE { get; set; }
    }
}
