//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PICTUREARCHIVE
    {
        public string NETNAME { get; set; }
        public byte[] PICTURE { get; set; }
        public string STATUS { get; set; }
        public System.DateTime TIMESTAMP { get; set; }
    
        public virtual STUDENT STUDENT { get; set; }
    }
}
