//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        public string NETNAME { get; set; }
        public int ID { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public bool VALID { get; set; }
        public System.DateTime DOB { get; set; }
        public bool PENDING { get; set; }
        public byte[] PROFILEPICTURE { get; set; }
        public byte[] PENDINGPICTURE { get; set; }
        public string UGRADSTATUS { get; set; }
        public System.DateTime EXPIREDATE { get; set; }
        public bool UPDATEPICTURE { get; set; }
    
        public virtual PICTUREARCHIVE PICTUREARCHIVE { get; set; }
    }
}
